# Generated by Django 3.2.15 on 2022-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_base_price', models.FloatField()),
                ('dist_additional_price', models.FloatField()),
                ('time_factor_multi', models.IntegerField()),
                ('additional_distance', models.FloatField()),
                ('is_admin', models.BooleanField(default=True)),
            ],
        ),
    ]
